[package]
name = "evm-contracts-test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ethers.workspace = true
evm-contracts-rs.workspace = true
tracing.workspace = true

[dev-dependencies]
rstest.workspace = true
test-log.workspace = true
tokio.workspace = true
