# https://github.com/crate-ci/typos/blob/master/docs/reference.md
[files]
extend-exclude = ["axelar-amplifier", "evm-contracts/lib/*", "offchain", "solana/xtask/devnet-amplifier.json"]

[default]
extend-ignore-identifiers-re = [
  "gtwgM94UYHwBh3g7rWi1tcpkgELxHQRLPpPHsaECW57",
]
