[package]
name = "program-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rkyv = { workspace = true, features = ["validation"] }
borsh.workspace = true
bytemuck.workspace = true
bytemuck_derive.workspace = true
solana-program.workspace = true

[dev-dependencies]
