[package]
name = "governance-gmp"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
hex.workspace = true

[dev-dependencies]
ethers.workspace = true
