[package]
name = "event-cpi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anchor-discriminators.workspace = true
borsh.workspace = true
solana-program.workspace = true
