[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
memo_program = "5fzGoxYfSbCvNR47tczb55wejYAyfeEhkE5f4Qnw4nKz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-memo = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memo-program.ts"
test-gateway = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gateway.ts"
test-its = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/its.ts"