on:
  push:
    branches: [main]
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash    

name: unused-deps
jobs:
  unused-deps:
    runs-on: self-hosted
    name: unused-deps
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: cargo xtask unused-deps
        run: cargo xtask unused-deps
